"""empty message

Revision ID: 672239415eaa
Revises: 
Create Date: 2018-11-15 13:22:00.753347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672239415eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('superior', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cr_date', sa.Date(), nullable=True),
    sa.Column('cancel_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['superior'], ['depts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depts_name'), 'depts', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('superior', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('entrydate', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('office_location', sa.Integer(), nullable=True),
    sa.Column('job_state', sa.Integer(), nullable=True),
    sa.Column('can_login', sa.Boolean(), nullable=True),
    sa.Column('profile', sa.String(length=200), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('cr_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['depts.id'], ),
    sa.ForeignKeyConstraint(['superior'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('companys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('profile', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.Integer(), nullable=True),
    sa.Column('userlevel', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('homepage', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('reg_from', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=50), nullable=True),
    sa.Column('consultant', sa.Integer(), nullable=True),
    sa.Column('cr_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['consultant'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companys_email'), 'companys', ['email'], unique=True)
    op.create_index(op.f('ix_companys_industry'), 'companys', ['industry'], unique=False)
    op.create_index(op.f('ix_companys_mobile'), 'companys', ['mobile'], unique=True)
    op.create_index(op.f('ix_companys_name'), 'companys', ['name'], unique=False)
    op.create_index(op.f('ix_companys_username'), 'companys', ['username'], unique=True)
    op.create_table('permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('privilege', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=500), nullable=True),
    sa.Column('jobtype', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('online', sa.Date(), nullable=True),
    sa.Column('offline', sa.Date(), nullable=True),
    sa.Column('cr_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_companys_username'), table_name='companys')
    op.drop_index(op.f('ix_companys_name'), table_name='companys')
    op.drop_index(op.f('ix_companys_mobile'), table_name='companys')
    op.drop_index(op.f('ix_companys_industry'), table_name='companys')
    op.drop_index(op.f('ix_companys_email'), table_name='companys')
    op.drop_table('companys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_depts_name'), table_name='depts')
    op.drop_table('depts')
    # ### end Alembic commands ###
