"""empty message

Revision ID: 6a3ab007289b
Revises: 
Create Date: 2018-11-12 21:09:00.692869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3ab007289b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('superior', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cr_date', sa.Date(), nullable=True),
    sa.Column('cancel_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['superior'], ['depts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depts_name'), 'depts', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('superior', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('entrydate', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('office_location', sa.Integer(), nullable=True),
    sa.Column('job_state', sa.Integer(), nullable=True),
    sa.Column('can_login', sa.Boolean(), nullable=True),
    sa.Column('profile', sa.String(length=200), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('cr_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['depts.id'], ),
    sa.ForeignKeyConstraint(['superior'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('permissions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('privilege', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_depts_name'), table_name='depts')
    op.drop_table('depts')
    # ### end Alembic commands ###
