"""empty message

Revision ID: efa4d3f071e4
Revises: 672239415eaa
Create Date: 2018-11-15 13:40:11.624802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efa4d3f071e4'
down_revision = '672239415eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('companyname', sa.String(length=20), nullable=True))
    op.add_column('companys', sa.Column('hr_name', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_companys_companyname'), 'companys', ['companyname'], unique=False)
    op.create_index(op.f('ix_companys_hr_name'), 'companys', ['hr_name'], unique=False)
    op.drop_index('ix_companys_name', table_name='companys')
    op.drop_column('companys', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('name', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('ix_companys_name', 'companys', ['name'], unique=False)
    op.drop_index(op.f('ix_companys_hr_name'), table_name='companys')
    op.drop_index(op.f('ix_companys_companyname'), table_name='companys')
    op.drop_column('companys', 'hr_name')
    op.drop_column('companys', 'companyname')
    # ### end Alembic commands ###
